'''ORMUCO'S SOFTWARE DEVELOPER AI & ML - TECHNICAL TEST, Question C

Create an api that takes a string as input and returns a
list of text insights from the top 5 google results of
the query generated by those keywords. 

Test with the following string « keystone - Circular reference found
role inference » . You will need to build a query , search the web
(you can scrape google) , select the top 5 results and
for each result scrape for the most relevant information on that page
relevant from a user’s perspective based on the original string ).
The response should contain the links to the websites that were
scraped with the most relevant
information (could be a text insight ,  a code snippet, a patch
file, etc.) for each. In the response, feel free
to add any other extra information that you think could be relevant.

As a hint, we are not looking for quantity, but rather quality,
maintainability, scalability, testability and a code that you can
be proud of.

When submitting your code add the necessary documentation to
explain your overall design and missing functionalities. 

Good Luck, name the test using the convention 
firstname_lastname_test and provide a link in your personal
github so we can review the work.
'''

def api(string_input, n = 5):
    # query google for the first n top results of the query

